server {
	listen 8080;
	server_name localhost;
	
	root ./www;
	
	index index.html;
	
	autoindex off;
	
	error_page 404 /error_pages/404_copy.html;
	error_page 403 /error_pages/403.html;
	error_page 500 /error_pages/500.html;
	
	client_max_body_size 100M;
	
	location / {
		allow all;
	}
	
	location /uploads {
        root ./www;
        allow POST;
        allow GET;
    }

	location /cgi-bin {
		allowed_methods GET POST;
		cgi_enabled on;
	}
	
	location ~ \.py$ {
		allowed_methods GET POST;
		cgi_enabled on;
		cgi_path /usr/bin/python3;
	}
	
	location ~ \.php$ {
        allowed_methods GET POST;
        cgi_enabled on;
        cgi_path /usr/bin/php-cgi;
        cgi_extension .php;
    }
    
    location ~ \.pl$ {
        allowed_methods GET POST;
        cgi_enabled on;
        cgi_path /usr/bin/perl;
        cgi_extension .pl;
    }
}
