# Servidor A - Para teste de conflito de portas entre processos
# Este arquivo usa as portas 8080 e 8081

server {
    listen 8080;
    server_name server-a.local;
    host 0.0.0.0;
    
    root ./www;
    index index.html;
    
    client_max_body_size 1M;
    autoindex on;
    
    error_page 404 /error_pages/404.html;
}

server {
    listen 8081;
    server_name server-a-alt.local;
    host 0.0.0.0;
    
    root ./www;
    index index.html;
    
    client_max_body_size 5M;
}
